language: ruby
rvm:
  - "2.3.5"
gemfile:
  - gemfiles/ar_3.2.gemfile
  - gemfiles/ar_4.0.gemfile
  - gemfiles/ar_4.1.gemfile
  - gemfiles/ar_4.2.gemfile
  - gemfiles/ar_5.0.gemfile
  - gemfiles/ar_5.1.gemfile
script: "bundle exec rake"
